### ISSUE TITLE
Group and Round connection.

### ISSUE THREAD

**Issue by Bogusik** [Drarig29/brackets-model#3] opened 2021-03-10 13:35 UTC
Hello, what is the algorithm to create Groups for Round objects? I found this types, but I have no idea how many Groups do I need to display tournament grid.
```
/**
 * A group of a stage.
 */
export interface Group {
    /** ID of the group. */
    id: number,

    /** ID of the parent stage. */
    stage_id: number,

    /** The number of the group in its stage. */
    number: number,
}

/**
 * A round of a group.
 */
export interface Round {
    /** ID of the round. */
    id: number,

    /** ID of the parent stage. */
    stage_id: number,

    /** ID of the parent group. */
    group_id: number,

    /** The number of the round in its group. */
    number: number,
}
```

**Comment by Drarig29** [comment] 2021-03-10 15:26
Duplicate of https://github.com/Drarig29/brackets-viewer.js/issues/42

**Closed by Drarig29** 2021-03-10 15:26 UTC
